// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_PUBLIC_GITHUB_URL: string;

  NEXT_PUBLIC_REDIRECT_URL: string;
  NEXT_PUBLIC_REDIRECT_TEXT: string;
  NEXT_PUBLIC_REDIRECT_HIDDEN: boolean;

  NEXT_PUBLIC_BANNER_URL: string;
  NEXT_PUBLIC_BANNER_TEXT: string;
  NEXT_PUBLIC_BANNER_HIDDEN: boolean;

  NEXT_PUBLIC_ANNOUNCEMENT_URL: string;
  NEXT_PUBLIC_ANNOUNCEMENT_TEXT: string;
  NEXT_PUBLIC_ANNOUNCEMENT_BUTTON_TEXT: string;
  NEXT_PUBLIC_ANNOUNCEMENT_HIDDEN: boolean;
}
